### PR TITLE
Fixes Seed inconsistency among workers

### PR DESCRIPTION
**Pull request by pdeubel**
Replaced `random` with `np.random` to generate random Integers. Oddly enough this fixes different results in the `TestExperiment.test_run()` test case, maybe random does not work well with parallel processing.

Note that I removed all `accepted_results` and inserted two new ones, which should be the correct ones:
```python
accepted_results = [
    -103.4065390603272,  # standard NumPy
    -102.16727461334207  # NumPy + MKL
]
```

The first is for using standard NumPy and the other is NumPy with the [Intel Math Kernel Library](https://software.intel.com/content/www/us/en/develop/articles/numpyscipy-with-intel-mkl.html). Seems like that Intel MKL does some things that change the results.

I tested the values by creating three new conda environments with Python3.6, Python3.7 and Python3.8 respectively. I simply executed `pip install --upgrade -r requirements.txt` for the setup and changed nothing else on the environments. Then I executed the test case and got the first value for every environment.
Then I did `pip uninstall numpy` followed by a `conda install numpy` which installs NumPy with MKL extensions. After executing the test case I got the second value for each environment.

@bjuergens Could you test if you have the same value when you checkout this branch? What Python version are you using? Do you use Intel MKL?

### CODE REVIEW

**Comment by bjuergens** [comment]
kann reviewt/germergt werden?

**Comment by pdeubel** [comment]
Ne noch nicht -> habs in Draft umgewandelt

**Comment by pdeubel** [comment]
Bzw siehe https://github.com/neuroevolution-ai/NeuroEvolution-CTRNN_new/pull/46#issuecomment-760391580

**Comment by bjuergens** [comment]
> habs in Draft umgewandelt

cool. wusste garnicht , dass das geht

willst du hier noch etwas konkretes implementieren/ändern? Falls nein, würde ich das einfach schonmal reinmergen

**Comment by pdeubel** [comment]
Ich teste noch ein zwei Sachen ansonsten merge ich einfach und schreibe den Wert den der Action Runner ausgibt in den Test rein -> Dann läuft der immer durch hoffentlich

**Pull request merged**
